nohup: ignoring input
Traceback (most recent call last):
  File "/home/pgrad1/2633042r/Multioutput_FixedG_GP/RealCase_pca_PE.py", line 3, in <module>
    import pandas as pd
  File "/home/pgrad1/2633042r/miniconda3/envs/GT/lib/python3.10/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/pgrad1/2633042r/miniconda3/envs/GT/lib/python3.10/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/home/pgrad1/2633042r/miniconda3/envs/GT/lib/python3.10/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/pgrad1/2633042r/miniconda3/envs/GT/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 68, in <module>
    from pandas.core.frame import DataFrame
  File "/home/pgrad1/2633042r/miniconda3/envs/GT/lib/python3.10/site-packages/pandas/core/frame.py", line 149, in <module>
    from pandas.core.generic import (
  File "/home/pgrad1/2633042r/miniconda3/envs/GT/lib/python3.10/site-packages/pandas/core/generic.py", line 193, in <module>
    from pandas.core.window import (
  File "/home/pgrad1/2633042r/miniconda3/envs/GT/lib/python3.10/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (
  File "/home/pgrad1/2633042r/miniconda3/envs/GT/lib/python3.10/site-packages/pandas/core/window/ewm.py", line 11, in <module>
    import pandas._libs.window.aggregations as window_aggregations
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/pgrad1/2633042r/miniconda3/envs/GT/lib/python3.10/site-packages/pandas/_libs/window/aggregations.cpython-310-x86_64-linux-gnu.so)
